# Generated by Django 3.0 on 2022-01-31 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220131_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
